export const SALE_ORDER_PAGE_PERMISSION = "page.sale-orders.view";

export const SALE_ORDER_PERMISSIONS = {
  view: "sale_orders.view",
  viewAll: "sale_orders.view_all",
  viewDetail: "sale_orders.view_detail",
  viewDeleted: "sale_orders.view_deleted",
  viewStatistics: "sale_orders.view_statistics",
  viewCustomerData: "sale_orders.view_customer_data",
  viewAmounts: "sale_orders.view_amounts",
  viewProducts: "sale_orders.products.view",
  viewStock: "sale_orders.stock.view",
  create: "sale_orders.create",
  update: "sale_orders.update",
  delete: "sale_orders.delete",
  restore: "sale_orders.restore",
  clientsManage: "sale_orders.clients.manage",
  assignAdviser: "sale_orders.assign_adviser",
  assignWorkflow: "sale_orders.assign_workflow",
  changeState: "sale_orders.change_state",
  executeWorkflowAction: "sale_orders.execute_workflow_action",
  cancel: "sale_orders.cancel",
  confirmDelivery: "sale_orders.confirm_delivery",
  viewHistory: "sale_orders.view_history",
  viewAudit: "sale_orders.view_audit",
  viewPayments: "sale_orders.payments.view",
  createPayment: "sale_orders.payments.create",
  updatePayment: "sale_orders.payments.update",
  deletePayment: "sale_orders.payments.delete",
  viewAttachments: "sale_orders.attachments.view",
  uploadAttachment: "sale_orders.attachments.upload",
  deleteAttachment: "sale_orders.attachments.delete",
  import: "sale_orders.import",
  viewImportLotes: "sale_orders.import_lotes.view",
  manageImportLotes: "sale_orders.import_lotes.manage",
  export: "sale_orders.export",
  viewPdf: "sale_orders.pdf.view",
  viewWorkflows: "sale_orders.workflows.view",
  manageWorkflows: "sale_orders.workflows.manage",
} as const;
