export {default as Home } from './Home'
export {default as Login } from './Auth/Login'
export {default as Register } from './Auth/Register'
// export {default as Profile } from './Profile'
// export {default as Order } from './Order'
// export {default as NotFound } from './NotFound'